version: '3.8'

services:
  kratos-migrate:
    image: oryd/kratos:v1.1.0
    environment:
      - DSN=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-secret}@db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./deploy/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    networks:
      - default

  kratos:
    image: oryd/kratos:v1.1.0
    depends_on:
      - kratos-migrate
      - mailslurper
    ports:
      - '4433:4433' # Public
      - '4434:4434' # Admin
    environment:
      - DSN=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-secret}@db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./deploy/kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev
    networks:
      - default

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    ports:
      - "4455:3000"  # External:Internal - UI runs on port 3000 internally
    environment:
      - KRATOS_PUBLIC_URL=http://127.0.0.1:4433
      - KRATOS_ADMIN_URL=http://127.0.0.1:4434
      - COOKIE_SECRET=super-secret-cookie-secret-1234
      - CSRF_COOKIE_NAME=ory_kratos_csrf
      - CSRF_COOKIE_SECRET=super-secret-csrf-secret-1234
    depends_on:
      - kratos
    networks:
      - default

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4438:4436'
      - '4437:4437'
      - '2500:2500'
    networks:
      - default
