version: v0.10.1

dsn: ${KRATOS_DSN}

serve:
  public:
    base_url: ${KRATOS_PUBLIC_BASE_URL}
    cors:
      enabled: true
      allowed_origins:
        - https://karima.com
        - https://admin.ks-backend.cloud
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: ${KRATOS_ADMIN_BASE_URL}

selfservice:
  default_browser_return_url: ${KRATOS_DEFAULT_RETURN_URL}
  allowed_return_urls:
    - ${KRATOS_DEFAULT_RETURN_URL}
    - https://karima.com/
    - https://admin.ks-backend.cloud/

  methods:
    password:
      enabled: true
    # oidc:
    #   enabled: false

  flows:
    error:
      ui_url: ${KRATOS_UI_URL}/error

    settings:
      ui_url: ${KRATOS_UI_URL}/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: ${KRATOS_UI_URL}/recovery

    verification:
      enabled: true
      ui_url: ${KRATOS_UI_URL}/verification
      after:
        default_browser_return_url: ${KRATOS_DEFAULT_RETURN_URL}

    logout:
      after:
        default_browser_return_url: ${KRATOS_UI_URL}/login

    login:
      ui_url: ${KRATOS_UI_URL}/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: ${KRATOS_UI_URL}/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: ${KRATOS_LOG_LEVEL:-info}
  format: ${KRATOS_LOG_FORMAT:-json}
  leak_sensitive_values: ${KRATOS_LEAK_SENSITIVE_VALUES:-false}

secrets:
  cookie:
    - ${KRATOS_SECRET_COOKIE}
  cipher:
    - ${KRATOS_SECRET_CIPHER}

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: ${KRATOS_SMTP_CONNECTION_URI}
